const fs = require('fs')
console.log((process.hrtime()[0]/60).toFixed(5))
console.log('Antes da leitura do arquive')
const data = fs.readFileSync('file.txt')
console.log('Executando o console após o arquive')
console.log((process.hrtime()[0]/60).toFixed(5))